[mgr]
# linemode = "size"

[opener]
sender = [
  { run = 'sender -f %s', block = true, for = "unix", desc = "P2p Sender..." },
  { run = 'sender -f %s', block = true, for = "windows", desc = "P2p Sender..." },
]
receiver = [
  { run = 'receiver', block = true, for = "unix", desc = "P2p Receiver..." },
  { run = 'receiver', block = true, for = "windows", desc = "P2p Receiver..." },
]

[open]
rules = [
	# Folder
	{ url = "*/", use = [ "edit", "open", "reveal", "sender", "receiver" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal", "sender", "receiver" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal", "sender", "receiver" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal", "sender", "receiver" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal", "sender", "receiver" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal", "sender", "receiver" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal", "sender", "receiver" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download" },
	# Fallback
	{ url = "*", use = [ "open", "reveal", "sender", "receiver" ] },
]

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
